INSERT IGNORE INTO roles(name) VALUES ('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_HR');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_LAB');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_QUALITY');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_SALE');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_NOT_SPECIFIED');
